[stable/2023.1] fix: update go dependencies #2003 (#2008)
oras-go is the main reason.
types.AuthConfig is deprecated in docker v25.x.x.
This causes unit test failure.
/go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:44:20: undefined: types.AuthConfig /go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:62:131: undefined: types.AuthConfig /go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:122:32: undefined: types.AuthConfig /go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login.go:54:16: undefined: types.AuthConfig oras-go is indirect dep belonging to helm.sh/helm/v3. Since v3.15.2, helm uses 1.2.5 oras-go.
Btw, I updated helm to v3.16.2.
here are references.
oras-project/oras-go#691 oras-project/oras-go#697 https://github.com/helm/helm/releases/tag/v3.15.2
fix #2003
Depends-On: #2026