fix: update go dependencies
oras-go is the main reason.
types.AuthConfig is deprecated in docker v25.x.x.
This causes unit test failure.
```
/go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:44:20: undefined: types.AuthConfig
/go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:62:131: undefined: types.AuthConfig
/go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:122:32: undefined: types.AuthConfig
/go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login.go:54:16: undefined: types.AuthConfig
```

oras-go is indirect dep belonging to helm.sh/helm/v3.
since v3.15.2, helm uses 1.2.5 oras-go.

here are references.
https://github.com/oras-project/oras-go/issues/691
https://github.com/oras-project/oras-go/issues/697
https://github.com/helm/helm/releases/tag/v3.15.2